### ISSUE TITLE
rules should only check jasmine functions.

### ISSUE THREAD

**Issue by sorahn** [djungowski/tslint-jasmine#1]
I came here via your [stackoverflow answer](https://stackoverflow.com/a/51403701) and I tried this out, but I have some other files that have a `.fit` function which the linter fails for.

Can the linter be made to ignore these?

<img width="509" alt="Screen Shot 2019-11-25 at 1 58 19 PM" src="https://user-images.githubusercontent.com/588852/69542416-b2089880-0f8b-11ea-8705-8810449d26a1.png">

**Comment by djungowski** [comment]
Fixed in Version 1.0.2 - Thanks for the report!
